import { test, expect } from '@playwright/test'

test('real PostgreSQL: bare clarification replies, invalid input, reload and HITL', async ({ page }) => {
  test.skip(!process.env.FRONTEND_E2E, 'Requires isolated seeded PostgreSQL')
  async function send(message: string) {
    await page.getByLabel('消息', { exact: true }).fill(message)
    const response = page.waitForResponse(r => r.url().endsWith('/agent/requests') && r.request().method() === 'POST')
    await page.getByRole('button', { name: '发送 ↑', exact: true }).click()
    const reply = await response
    expect(reply.ok()).toBeTruthy()
    await expect(page.locator('.loading')).toHaveCount(0)
    return reply.json()
  }
  async function reload() {
    await page.reload()
    await expect(page.getByLabel('消息', { exact: true })).toBeEnabled()
  }
  await page.goto('/')
  await expect(page.getByLabel('消息', { exact: true })).toBeEnabled()
  let row = await send('查询订单')
  expect(row.result.question).toBe('order')
  await reload()
  row = await send('SEED O003!')
  expect(row.result.question).toBe('order')
  await expect(page.locator('.answer').last()).toContainText('格式错误')
  await reload()
  const order = await send('SEED-O003')
  expect(order.result.evidence[0].result.source).toBe('get_order')
  const item = order.result.evidence[0].result.data.items[0].id
  expect((await send('查询物流')).result.question).toBe('order')
  await reload()
  expect((await send('SEED-O003')).result.evidence[0].result.source).toBe('get_logistics')
  expect((await send('帮我取消这个订单')).result.question).toBe('order')
  expect((await send('SEED-O001')).result.question).toBe('reason')
  await reload()
  row = await send('不需要了')
  expect(row.status).toBe('waiting_for_confirmation')
  await expect(page.getByRole('region', { name: '操作确认' })).toContainText('SEED-O001')
  await page.getByRole('button', { name: '＋ 新建会话', exact: true }).click()
  expect((await send('申请退款，原因 尺码不合适')).result.question).toBe('order')
  expect((await send('SEED-O003')).result.question).toBe('order_item')
  await reload()
  expect((await send(item)).result.question).toBe('quantity')
  expect((await send('1')).result.question).toBe('amount')
  row = await send('59.00')
  expect(row.status).toBe('waiting_for_confirmation')
  expect(row.draft.parameters.order_item_id).toBe(item)
  await expect(page.getByRole('region', { name: '操作确认' })).toContainText('创建退款申请')
  await page.screenshot({ path: '../output/playwright/clarification-refund.png', fullPage: true })
})

test('real PostgreSQL: queries, evidence, HITL, reload and receipts', async ({ page }) => {
  test.skip(!process.env.FRONTEND_E2E, 'Run python -m scripts.frontend_e2e for an isolated seeded PostgreSQL database')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {
    if (request.method() === 'POST' && request.url().includes('/agent/')) {
      const body = request.postDataJSON()
      expect(Object.keys(body).sort()).toEqual(request.url().endsWith('/resume') ? ['decision', 'operation_id']
        : body.clarification_thread_id ? ['clarification_thread_id', 'message', 'request_key'] : ['message', 'request_key'])
    }
  })
  async function send(message: string) {
    await page.getByLabel('消息', { exact: true }).fill(message)
    const response = page.waitForResponse(r => r.url().endsWith('/agent/requests') && r.request().method() === 'POST')
    await page.getByRole('button', { name: '发送 ↑', exact: true }).click()
    const reply = await response
    expect(reply.ok()).toBeTruthy()
    const workflow = await reply.json()
    await expect(page.locator('.loading')).toHaveCount(0)
    return workflow
  }
  await page.goto('/')
  await expect(page.locator('.sidebar-bottom')).toContainText('模拟消费者甲')
  await expect(page.locator('.topbar .provider-badge')).toContainText('Fake Provider')
  await expect(page.locator('.provider-note')).toHaveCount(0)
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '＋ 新建会话', exact: true }).click()
  await expect(page.locator('.session-list button')).toHaveCount(0)
  for (const width of [1440, 1920]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    expect((await page.locator('.evidence-panel').boundingBox())!.width).toBeLessThan(260)
    await page.screenshot({ path: `../output/playwright/polish-empty-${width}.png`, fullPage: true })
  }
  const product = await send('查询商品 纯棉短袖')
  expect(product.result.evidence[0].result.source).toBe('search_products')
  await expect(page.getByRole('complementary', { name: '证据详情' })).toContainText('SEED-P001')
  await expect(page.getByRole('button', { name: '刷新请求状态', exact: true })).toHaveCount(0)
  await expect(page.locator('.request-details')).not.toHaveAttribute('open')
  await expect(page.locator('.tool-details')).not.toBeVisible()
  await expect(page.locator('.session-list button')).toHaveCount(1)
  for (const width of [1440, 1920]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    expect((await page.locator('.evidence-panel').boundingBox())!.width).toBeGreaterThan(300)
    await page.screenshot({ path: `../output/playwright/polish-product-${width}.png`, fullPage: true })
  }
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '＋ 新建会话', exact: true }).click()
  await expect(page.locator('.session-list button')).toHaveCount(1)
  await expect(page.locator('.evidence-card')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.sidebar-bottom')).toContainText('模拟消费者甲')
  await expect(page.locator('.session-list button')).toHaveCount(1)
  await expect(page.locator('.turn')).toHaveCount(0)
  await page.locator('.session-list button').first().click()
  await expect(page.locator('.evidence-panel')).toContainText('SEED-P001')
  await expect(page.getByLabel('消息', { exact: true })).toBeEnabled()
  const sku = await send('查询 SKU 纯棉短袖')
  expect(sku.result.evidence.some((e: any) => e.result.source === 'list_product_skus')).toBeTruthy()
  const turns = await page.locator('.turn').evaluateAll(nodes => nodes.map(node => {
    const rect = node.getBoundingClientRect(); return { top: rect.top, bottom: rect.bottom }
  }))
  expect(turns[1].top - turns[0].bottom).toBeLessThanOrEqual(24)
  await page.screenshot({ path: '../output/playwright/compact-chat.png', fullPage: true })
  const stock = await send('查询库存 纯棉短袖 白色 M')
  expect(stock.result.evidence.at(-1).result.data.stocks[0].available).toBe(17)
  await expect(page.locator('.stock-number')).toHaveText('17')
  const order = await send('查询订单 SEED-O003')
  const orderData = order.result.evidence[0].result.data
  expect(orderData.order_no).toBe('SEED-O003')
  await expect(page.locator('.evidence-panel')).toContainText('部分发货')
  const logistics = await send('查询物流 SEED-O003')
  expect(logistics.result.evidence[0].result.data.packages[0].tracking_no).toBe('SEED-TRACK-partial')
  await expect(page.locator('.evidence-panel')).toContainText('模拟运输中')
  const policy = await send('查询七天无理由退货政策')
  const hit = policy.result.evidence[0].result.data[0]
  expect(hit.title).toBeTruthy(); expect(hit.version).toBeGreaterThan(0); expect(hit.locator).toBeTruthy()
  await expect(page.locator('.evidence-panel')).toContainText(hit.title)
  await expect(page.locator('blockquote').first()).toContainText(hit.content)
  await page.screenshot({ path: '../output/playwright/product-desktop.png', fullPage: true })

  // Clarify and tool denial go through the actual model/tool/backend.
  expect((await send('查询订单')).result.kind).toBe('clarify')
  await expect(page.locator('.evidence-panel')).toContainText(hit.title)
  await expect(page.locator('.evidence-context')).toContainText('查询七天无理由退货政策')
  await expect(page.locator('.answer').last()).toContainText('SEED-O001')
  await page.getByRole('button', { name: '补充信息 ↗', exact: true }).click()
  await expect(page.getByLabel('消息', { exact: true })).toHaveValue('')
  await page.getByRole('button', { name: '资料 [1] · 商品', exact: true }).first().click()
  await expect(page.locator('.evidence-panel')).toContainText('SEED-P001')
  await expect(page.locator('.evidence-context')).toContainText('查询商品 纯棉短袖')
  await page.screenshot({ path: '../output/playwright/polish-clarify.png', fullPage: true })
  expect((await send('查询订单 SEED-O002')).result.evidence[0].result.status).toBe('forbidden')
  await expect(page.locator('.turn').last().locator('.evidence-links button')).toHaveCount(0)
  await expect(page.locator('.evidence-panel')).toContainText(hit.title)
  expect((await send('修改库存')).result.kind).toBe('reject')
  await send('查询订单 SEED-O003')
  await expect(page.locator('.evidence-panel')).toContainText('SEED-O003')
  const cancelMessage = '取消我的订单 SEED-O001，原因 不需要了'
  const rejected = await send(cancelMessage)
  expect(rejected.status).toBe('waiting_for_confirmation')
  await expect(page.getByRole('region', { name: '操作确认' })).toContainText('SEED-O001')
  await expect(page.locator('.operation-target')).toHaveText('当前操作目标：SEED-O001')
  await expect(page.locator('.evidence-panel')).not.toContainText('SEED-O003')
  await expect(page.locator('.evidence-panel')).toContainText('暂无关联业务资料')
  await expect(page.locator('.evidence-panel .count')).toHaveText('0')
  await expect(page.locator('.evidence-links button').last()).toBeDisabled()
  await page.screenshot({ path: '../output/playwright/hitl-target-empty.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('button', { name: '拒绝 / Reject', exact: true })).toBeEnabled()
  await expect(page.locator('.evidence-panel')).not.toContainText('SEED-O003')
  await expect(page.locator('.evidence-panel .count')).toHaveText('0')
  for (const answer of await page.locator('.answer').all()) await expect(answer).not.toContainText('"product_code":')
  const rejectResponse = page.waitForResponse(r => r.url().endsWith(`/threads/${rejected.thread_id}/resume`))
  await page.getByRole('button', { name: '拒绝 / Reject', exact: true }).click()
  expect((await (await rejectResponse).json()).status).toBe('rejected')
  await expect(page.getByText('已拒绝本次操作，未执行取消或退款申请。')).toBeVisible()
  await expect(page.locator('.operation-target')).toHaveCount(0)
  await expect(page.locator('.evidence-panel')).toContainText('SEED-O003')
  await expect(page.locator('.evidence-links button').last()).toBeEnabled()
  const unchanged = await send('查询订单 SEED-O001')
  expect(unchanged.result.evidence[0].result.data.status).toBe('pending_payment')

  const confirmed = await send(cancelMessage)
  expect(confirmed.thread_id).not.toBe(rejected.thread_id)
  await expect(page.locator('.operation-target')).toHaveText('当前操作目标：SEED-O001')
  await expect(page.locator('.evidence-panel .count')).toHaveText('1')
  await expect(page.locator('.evidence-card')).toContainText('SEED-O001')
  await expect(page.locator('.evidence-panel')).not.toContainText('SEED-O003')
  // The server really commits; only its HTTP response is dropped to test uncertainty handling.
  await page.route(`**/threads/${confirmed.thread_id}/resume`, async route => {
    const response = await route.fetch()
    expect((await response.json()).status).toBe('succeeded')
    await route.abort('failed')
  }, { times: 1 })
  await page.getByRole('button', { name: '确认执行 / Confirm', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('无法连接服务')
  await expect(page.getByText('订单已取消。后端已完成执行。')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '拒绝 / Reject', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByText('订单已取消。后端已完成执行。')).toBeVisible()
  const cancelled = await send('查询订单 SEED-O001')
  expect(cancelled.result.evidence[0].result.data.status).toBe('cancelled')

  const refund = await send(`申请退款 订单 SEED-O003，明细 ${orderData.items[0].id}，数量 1，金额 59.00，原因 尺码不合适`)
  expect(refund.status).toBe('waiting_for_confirmation')
  await expect(page.getByRole('region', { name: '操作确认' }).last()).toContainText('59.00 CNY')
  await expect(page.getByRole('button', { name: '确认执行 / Confirm', exact: true })).toBeInViewport()
  await page.screenshot({ path: '../output/playwright/product-hitl.png', fullPage: true })
  const refundResponse = page.waitForResponse(r => r.url().endsWith(`/threads/${refund.thread_id}/resume`))
  await page.getByRole('button', { name: '确认执行 / Confirm', exact: true }).click()
  const receipt = await (await refundResponse).json()
  expect(receipt.status).toBe('succeeded')
  expect(receipt.result.refund_status).toBe('requested')
  await expect(page.getByText(/退款申请已创建，状态：待处理/)).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: '../output/playwright/product-mobile.png', fullPage: true })
  await expect(page.locator('.provider-badge')).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: '＋ 新建会话', exact: true }).click()
  const missing = await send('查询商品 不存在的商品编号UI')
  expect(missing.result.evidence[0].result.status).toBe('not_found')
  await expect(page.locator('.evidence-panel .count')).toHaveText('0')
  await expect(page.locator('.evidence-card, .evidence-links button')).toHaveCount(0)
  await page.locator('.request-details > summary').click()
  await page.locator('.tool-details > summary').click()
  await expect(page.locator('.tool-row')).toContainText('未找到资料')
  await page.locator('.tool-record > summary').click()
  await expect(page.locator('.tool-record pre')).toContainText('not_found')
  await page.screenshot({ path: '../output/playwright/empty-evidence-details.png', fullPage: true })
  expect(errors).toEqual([])
})
